# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: NIU CSIE 程式設計社群
email: twbrandon7@gmail.com
description: # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sescies.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:  sescies
encoding: utf-8
timezone: Asia/Taipei

paginate: 5
paginate_path: "/page:num/"

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    block.line_numbers: true
redcarpet:
  extensions : ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
